language: python
before_script:
    - psql -c 'create database django_location;' -U postgres
    - createlang -U postgres plpgsql django_location
    - psql -U postgres -d django_location -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
    - psql -U postgres -d django_location -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.5.1 POSTGIS=1.5
install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install -q -e . --use-mirrors
script:
    - python setup.py test
