language: python
before_install: 
    - sudo apt-get install libspatialite-dev
python:
    - "2.6"
    - "2.7"
    - "3.2"
env:
    - DJANGO=1.5.1
    - POSTGIS=2.0
install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install -q -e . --use-mirrors
script:
    - python setup.py test
