language: python
before_script:
    - psql -c 'create database django_location;' -U postgres
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.5.1
install:
    - pip install psycopg2
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install -q -e . --use-mirrors
script:
    - python setup.py test
