language: python
addons:
  postgresql: "9.3"
before_script:
    - sudo apt-get update
    - sudo apt-get install -qq libgeos-dev libproj-dev postgis
    - createdb -E UTF8 django_location
    - psql -U postgres -d django_location -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;"
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.6.1
install:
    - pip install psycopg2
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install -q -e . --use-mirrors
script:
    - python setup.py test
